name: CD

on: [push]

env:
  CT_API_KEY: ${{ secrets.CT_API_KEY }}

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup operation environment
        run: |
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "master" ]]; then
            env="production"
          else
            env="development"
          fi
          echo "ENV=${env}" >> $GITHUB_ENV
      - name: Install cloudtruth cli
        run: |
          # Temporarily in s3 till we publish https://github.com/cloudtruth/cloudtruth-cli
          curl -Lsf https://ctdemo-development-sample-data.s3.amazonaws.com/bin/cloudtruth -o /tmp/cloudtruth
          chmod +x /tmp/cloudtruth
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Packages
        run: yarn install

      # Note that contents of .env are exposed in webapp, so while we treat the
      # TID as secret, it technically doesn't have to be
      - name: Configure react
        run: /tmp/cloudtruth -e ${ENV} template get deploy.web_dotenv  > .env

      - name: Build react
        run: yarn build

      - name: Deploy to S3
        run: |
          source <(/tmp/cloudtruth -e ${ENV} template get deploy.aws_credentials_env)
          source <(/tmp/cloudtruth -e ${ENV} template get deploy.web_env)
          aws s3 sync build/ s3://${BUCKET_NAME}/
          aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths /index.html /asset-manifest.json /manifest.json
