name: CD

on: [push]

env:
  CLOUDTRUTH_API_KEY: ${{ secrets.CLOUDTRUTH_API_KEY }}

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup operation environment
        run: |
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "master" ]]; then
            env="production"
          else
            env="development"
          fi
          echo "ENV=${env}" >> $GITHUB_ENV

      - name: Install cloudtruth cli
        uses: cloudtruth/cli-action@v1

      - uses: cloudtruth/configure-action@v1
        with:
          token: "${{ secrets.CLOUDTRUTH_API_KEY }}"
          project: "deploy"
          environment: "${{ env.ENV }}"
          overwrite: true

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Packages
        run: yarn install

      # Note that contents of .env are exposed in webapp, so while we treat the
      # TID as secret, it technically doesn't have to be
      - name: Configure react
        run: |
          cloudtruth -e ${ENV} --project deploy template get web_dotenv > .env
          cloudtruth -e ${ENV} --project web template get dotenv >> .env

      - name: Build react
        run: yarn build

      - name: Deploy to S3
        run: |
          aws s3 sync build/ s3://${WEB_BUCKET_NAME}/
          aws cloudfront create-invalidation --distribution-id ${WEB_DISTRIBUTION_ID} --paths /index.html /asset-manifest.json /manifest.json
