name: CD

on: [push]

env:
  CT_API_KEY: ${{ secrets.CT_API_KEY }}

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup operation environment
        run: |
          branch=${GITHUB_REF##*/}
          if [[ "$branch" == "master" ]]; then
            env="production"
          else
            env="development"
          fi
          echo "ENV=${env}" >> $GITHUB_ENV

      - name: Install cloudtruth cli
        uses: cloudtruth/cli-action@v1
        with:
          version: 0.1.3  


      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Packages
        run: yarn install

      # Note that contents of .env are exposed in webapp, so while we treat the
      # TID as secret, it technically doesn't have to be
      - name: Configure react
        run: |
          cloudtruth -e ${ENV} template get deploy.web_dotenv  > .env

      - name: Build react
        run: yarn build

      - name: Deploy to S3
        run: |
          source <(cloudtruth -e ${ENV} template get deploy.aws_credentials_env)
          source <(cloudtruth -e ${ENV} template get deploy.web_env)
          cloudtruth -e ${ENV} template get web.app.live_config > build/web.app.live_config.json
          aws s3 sync build/ s3://${BUCKET_NAME}/
          aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths /index.html /asset-manifest.json /manifest.json
